@startuml
left to right direction

skinparam defaultFontName Arial
skinparam backgroundcolor white

skinparam actor {
    BackgroundColor white
    BorderColor black
    FontColor black
}

skinparam usecase {
    BackgroundColor white
    BorderColor #333333
    FontColor black
}

skinparam rectangle {
    BackgroundColor #FFEBB5
    BorderColor #A67D3D
    FontColor black
    FontSize 18
    FontStyle bold
}

actor "Admin\n(Office)" as admin
actor "Passenger\n(Traveler)" as passenger
actor "Conductor\n(Staff)" as conductor

rectangle "NextStop Online System" {
  usecase "Add/Remove Buses" as UC1
  usecase "View Live Dashboard" as UC2
  usecase "Check Daily Earnings" as UC3
  
  usecase "Search Bus Routes" as UC4
  usecase "Track Bus Live Location" as UC5
  usecase "Book e-Ticket" as UC6
  
  usecase "Issue Physical Tickets" as UC7
  usecase "Scan Passenger QR Codes" as UC8
  usecase "Upload Offline Ticket Data" as UC9
}

admin --> UC1
admin --> UC2
admin --> UC3

passenger --> UC4
passenger --> UC5
passenger --> UC6

conductor --> UC7
conductor --> UC8
conductor --> UC9

@enduml
